# Machine Project
This is the start of the project

In [5]:
import os #to check working directory
import numpy as py
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
path = os.getcwd()  #in case your database isn't in the same folder as your notebook
path

'C:\\Users\\cacat\\OneDrive - De La Salle University - Manila\\Desktop\\Inbox\\Academe\\2023-2024\\TERM 3 (MAY-SEPT)\\CSMODEL\\Machine Project'

In [9]:
#make sure to change the directory according to where your BRFSS is located 
brfss_df = pd.read_csv("2015.csv")
brfss_df.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE         SEQNO  \
0     1.0     1.0  b'01292015'  b'01'  b'29'  b'2015'    1200.0  2.015000e+09   
1     1.0     1.0  b'01202015'  b'01'  b'20'  b'2015'    1100.0  2.015000e+09   
2     1.0     1.0  b'02012015'  b'02'  b'01'  b'2015'    1200.0  2.015000e+09   
3     1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0  2.015000e+09   
4     1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0  2.015000e+09   

           _PSU  CTELENUM  ...  _PAREC1  _PASTAE1  _LMTACT1  _LMTWRK1  \
0  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   
1  2.015000e+09       1.0  ...      2.0       2.0       3.0       3.0   
2  2.015000e+09       1.0  ...      9.0       9.0       9.0       9.0   
3  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   
4  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   

   _LMTSCL1  _RFSEAT2  _RFSEAT3  _FLSHOT6  _PNEUMO2  _AIDTST3  
0       1.0       1.0       1.0       NaN       NaN       1.0  
1       4.0       2.0       2.0       NaN       NaN       2.0  
2       9.0       9.0       9.0       9.0       9.0       NaN  
3       1.0       1.0       1.0       NaN       NaN       9.0  
4       1.0       1.0       1.0       NaN       NaN       1.0  

[5 rows x 330 columns]

In [10]:
selected_vars = ['DIABETE3', 'SEX','_RFHLTH', '_AGE_G', '_INCOMG', '_RFCHOL', '_EDUCAG', 'FRUTDA1_', 'GRENDAY_', '_RFHYPE5', '_PACAT1', 'CVDSTRK3', '_LTASTH1', 'MARITAL', 'DIFFWALK', '_BMI5CAT', '_RFBING5', 'SMOKE100']

In [11]:
diabetes_df=brfss_df[selected_vars]
diabetes_df = diabetes_df.query('SEX == 2') #we're only going to be working with female respondents 
diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254518 entries, 0 to 441455
Data columns (total 18 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   DIABETE3  254518 non-null  float64
 1   SEX       254518 non-null  float64
 2   _RFHLTH   254518 non-null  float64
 3   _AGE_G    254518 non-null  float64
 4   _INCOMG   254518 non-null  float64
 5   _RFCHOL   224553 non-null  float64
 6   _EDUCAG   254518 non-null  float64
 7   FRUTDA1_  234163 non-null  float64
 8   GRENDAY_  233464 non-null  float64
 9   _RFHYPE5  254518 non-null  float64
 10  _PACAT1   254518 non-null  float64
 11  CVDSTRK3  254518 non-null  float64
 12  _LTASTH1  254518 non-null  float64
 13  MARITAL   254518 non-null  float64
 14  DIFFWALK  247470 non-null  float64
 15  _BMI5CAT  225976 non-null  float64
 16  _RFBING5  254518 non-null  float64
 17  SMOKE100  246419 non-null  float64
dtypes: float64(18)
memory usage: 36.9 MB


In [49]:
diabetes_df['DIABETE3'].value_counts()

DIABETE3
3.0    214124
1.0     31852
4.0      4546
2.0      3608
7.0       295
9.0        93
Name: count, dtype: int64

In [51]:
diabetes_df['DIABETE3'].unique()

array([3., 1., 4., 2., 7., 9.])

In [53]:
diabetes_df['DIABETE3'].median()

3.0

In [55]:
diabetes_df['DIABETE3'].mean()

2.7602212810095947

In [ ]:
# the 7.0 and 9.0 because it's unsure/refused AND its only 0.153% of the sample
# threshold = 5% | 0.05


In [12]:
#variables that are non-null: 
# _RFCHOL(weird kasi more than the total entries), FRUTDA1_  ,GRENDAY_  ,DIFFWALK  ,_BMI5CAT  ,SMOKE100  
diabetes_df['_RFCHOL'].value_counts()

_RFCHOL
1.0    130461
2.0     92088
9.0      2004
Name: count, dtype: int64

In [56]:
diabetes_df['_RFCHOL'].unique()

array([ 2.,  1., nan,  9.])

In [68]:
diabetes_df['FRUTDA1_'].isnull().value_counts()

FRUTDA1_
False    234163
True      20355
Name: count, dtype: int64

In [17]:
diabetes_df['FRUTDA1_'].unique()

array([3.30000000e+01, 1.70000000e+01,            nan, 1.00000000e+02,
       2.00000000e+02, 2.90000000e+01, 1.40000000e+01, 4.30000000e+01,
       2.70000000e+01, 5.39760535e-79, 6.70000000e+01, 7.00000000e+00,
       5.70000000e+01, 5.00000000e+01, 2.30000000e+01, 8.30000000e+01,
       3.00000000e+02, 1.30000000e+01, 1.00000000e+01, 5.00000000e+02,
       1.43000000e+02, 7.10000000e+01, 2.00000000e+01, 2.00000000e+00,
       8.60000000e+01, 4.00000000e+02, 4.00000000e+01, 4.70000000e+01,
       3.00000000e+00, 9.30000000e+01, 9.00000000e+01, 4.29000000e+02,
       2.14000000e+02, 8.00000000e+01, 2.17000000e+02, 7.00000000e+01,
       9.70000000e+01, 2.86000000e+02, 7.30000000e+01, 8.70000000e+01,
       1.67000000e+02, 6.00000000e+01, 1.07000000e+02, 7.70000000e+01,
       1.17000000e+02, 1.33000000e+02, 3.00000000e+01, 1.14000000e+02,
       6.00000000e+02, 5.30000000e+01, 2.00000000e+03, 7.00000000e+02,
       3.57000000e+02, 1.71000000e+02, 8.00000000e+02, 7.14000000e+02,
      

In [19]:
diabetes_df['GRENDAY_'].isnull().value_counts()

GRENDAY_
False    233464
True      21054
Name: count, dtype: int64

In [21]:
diabetes_df['GRENDAY_'].unique()

array([3.30000000e+01, 2.90000000e+01,            nan, 3.00000000e+00,
       5.70000000e+01, 1.00000000e+02, 7.00000000e+00, 1.30000000e+01,
       1.70000000e+01, 6.70000000e+01, 4.30000000e+01, 5.39760535e-79,
       2.30000000e+01, 5.00000000e+01, 4.00000000e+01, 2.70000000e+01,
       1.40000000e+01, 2.00000000e+02, 8.30000000e+01, 7.10000000e+01,
       1.00000000e+01, 1.33000000e+02, 2.00000000e+01, 4.70000000e+01,
       3.00000000e+02, 8.60000000e+01, 9.70000000e+01, 5.00000000e+02,
       4.29000000e+02, 4.00000000e+02, 5.30000000e+01, 6.00000000e+01,
       6.30000000e+01, 1.50000000e+02, 8.00000000e+01, 9.30000000e+01,
       1.67000000e+02, 3.70000000e+01, 3.00000000e+01, 1.14000000e+02,
       7.30000000e+01, 8.70000000e+01, 9.00000000e+01, 2.86000000e+02,
       7.00000000e+01, 1.43000000e+02, 2.14000000e+02, 1.71000000e+02,
       6.00000000e+02, 1.17000000e+02, 7.70000000e+01, 1.29000000e+02,
       1.57000000e+02, 1.03000000e+02, 3.57000000e+02, 1.73000000e+02,
      

In [23]:
diabetes_df['DIFFWALK'].isnull().value_counts()

DIFFWALK
False    247470
True       7048
Name: count, dtype: int64

In [25]:
diabetes_df['DIFFWALK'].value_counts()

DIFFWALK
2.0    196977
1.0     49119
7.0       875
9.0       499
Name: count, dtype: int64

In [84]:
diabetes_df['DIFFWALK'].unique()

array([ 1.,  2., nan,  7.,  9.])

In [27]:
diabetes_df['_BMI5CAT'].isnull().value_counts()

_BMI5CAT
False    225976
True      28542
Name: count, dtype: int64

In [29]:
diabetes_df['_BMI5CAT'].value_counts()

_BMI5CAT
2.0    84884
3.0    70190
4.0    65846
1.0     5056
Name: count, dtype: int64

In [33]:
diabetes_df['_BMI5CAT'].unique()

array([ 4.,  3.,  2.,  1., nan])

In [35]:
diabetes_df['SMOKE100'].isnull().value_counts()

SMOKE100
False    246419
True       8099
Name: count, dtype: int64

In [37]:
diabetes_df['SMOKE100'].value_counts()

SMOKE100
2.0    149366
1.0     95249
7.0      1081
9.0       723
Name: count, dtype: int64

In [39]:
diabetes_df['SMOKE100'].unique()

array([ 1., nan,  2.,  7.,  9.])